### ISSUE TITLE
3/21 Crossover Grading

### ISSUE THREAD

**Issue by mistylavender** [mistylavender/RedTailedHawks#10]
- [ ] Scrum Team GitHub pages (0.9/1)

- [ ] Individual GitHub pages (4/4)

- [ ] [GitHub pages](https://mistylavender.github.io/techtalks/techtalk1notes)
- [ ] [Repl](https://replit.com/@MistyLavender/Data-Structures#Menu.java)

**Comment by Navodit1603** [comment]
Crossover Check Point grading: 12/12 CHECKS = 4/4


 Individual GitHub pages (Evaluate for 10 checks)

1/1 - Describe Linked Lists, Describe Java Generic T

1/1 - One check, both are described in notes

Queue Add and Delete

1/1 - One check for comments
1/1 - One check for Add, running example
2/2 - Two checks for Delete, one for individual implementation of Delete and one for running example
Merge 2 Queues

1/1 - One check for comments
2/2 - Two checks, one for individual implementation of Merge method(s) and one for running example
Build Stack and reverse Queue Order- Two checks, class definition

1/1 - One check, comments and general-purpose tester
1/1 - One check, reverse order test case from Queue to Stack
