### ISSUE TITLE
Natasha Week 0 Grading

### ISSUE THREAD

**Issue by mistylavender** [mistylavender/RedTailedHawks#5]
- [ ] [Scrum Team GitHub pages](https://github.com/mistylavender/RedTailedHawks) 2/2
        Project pages
                Web Project: Project Description, Ideas, Wires, Success idea
                Embed Project: Hardware Idea, Project Description, Success idea
        Team Roles described, Project Owner described, [Scrum Board started](https://github.com/mistylavender/RedTailedHawks/projects/1)

- [ ] Individual GitHub pages 1.5/3 - need subpages on github
        [Data Structure Hacks](https://replit.com/join/shtgcacbqv-mistylavender)
        [Tech Talk Notes + Plan for AP Exam](https://mistylavender.github.io/techtalks/)

**Comment by sarahwxie** [comment]
**Final Grade: 4.5/5**
Scrum Team GitHub Pages (2/2):
* A GitHub pages exists, has a theme, and has all the required information (1/1)
* Team Roles are described (1/1)
Individual GitHub Pages (2.5/3):
*  Navigates notes and plans for Tech talk: (1/1)
* Test Prep plans (0.5/1) >> could be more detailed
* Data Structures Work  (1/1)
