### ISSUE TITLE
3/17 Crossover Grading

### ISSUE THREAD

**Issue by rkwreck** [mistylavender/RedTailedHawks#9]
- [x] Project Owner initial requirements and derivative tangibles
- [x] Requirements and Jobs assigned to each individuals listed on Scrum Board, including at least one in progress task

[READ.ME](https://github.com/mistylavender/RedTailedHawks)
[Scrum Board](https://github.com/mistylavender/RedTailedHawks/projects/1)

**Comment by Navodit1603** [comment]
#### Total Score: 1/1
* Have a Github page running with requirements (0.5/0.5)
* Have a scrum board with initial issues (0.5/0.5)

**Comment by jm1021** [comment]
Mr Coleman sponsor shared link of email.  Each student commits Art work and account.  Teacher provides link for work to students.  Design interaction key next step.  

.9/1
